### ISSUE TITLE
[Bug] Scenes over 3 hour long not showing

### ISSUE THREAD

**Issue by nickylass** [porn-vault/porn-vault#1000]
**Describe the bug**
I've been scratching my head lately to understand why certain scenes were not shown after being successfully imported.
I just discovered that the filter for scene duration is set to 180 minutes by default and this excludes any scene that might be longer than this. Setting the duration filter top limit to 0 shows the missing scenes, but it resets back to the bad behaviour when reloading

**To Reproduce**

Add a scene longer than 3 hours. It won't display by default

**Expected behavior**
All scenes should show when filters are set to their default values

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version [e.g. 0.24

**Comment by leadwolf** [comment]
Can't you just disable the duration filter, or are you specifically looking for scenes longer than 180mn ?

**Comment by nickylass** [comment]
You can, but it's counterintuitive: One would expect to see all scenes when filter is in its default state. In this case the default filter shows all scenes EXCEPT those over 180 minutes

**Comment by leadwolf** [comment]
If the default state was that the filter is disabled, it would be the same thing. But like you said, to make it more practical maybe another step could be added for unlimited length.
