### ISSUE TITLE
[Low priority] Optimize setLabels, setActors functions

### ISSUE THREAD

**Issue by boi123212321** [porn-vault/porn-vault#1005]
Currently the functions remove all references, then readd the new ones.
Instead, the functions could check the difference between the old and new set, and adjust accordingly, saving some database writes.

https://github.com/porn-vault/porn-vault/blob/dev/src/types/label.ts#L17

+ The setActors functions can be refactored into a single function like Label.setForItem(...).

https://github.com/porn-vault/porn-vault/blob/dev/src/types/scene.ts#L338
https://github.com/porn-vault/porn-vault/blob/dev/src/types/image.ts#L126

**Comment by leadwolf** [comment]
Done in https://github.com/leadwolf/porn-vault/tree/refactor/diff-array-set-item
