### ISSUE TITLE
[Feature] Allow the user to configure logging

### ISSUE THREAD

**Issue by leadwolf** [porn-vault/porn-vault#1039]
- Configure log level statically and/or dynamically via web ui
- Output logs to file
- Rework the logs page to allow searching, auto updating

**Comment by boi123212321** [comment]
There should also be a generic logError function that deals with all the catch cases, because right now the error has to be typed manually like `const _err = error as Error;` for Typescript,.

**Comment by leadwolf** [comment]
I just figured out why it doesn't allow you to directly type a 'catched' value as Error. If you did `throw "some string"`, that obviously isn't an `Error`. But we are allowed to check `err instanceOf Error`, and then it'll allow `err as Error` without complaining

**Comment by boi123212321** [comment]
Maybe use winston, set log level in config etc.

**Comment by boi123212321** [comment]
Also a generic handleError function would be useful, that way all errors go into a centralized handler, something like:
```typescript
function handleError(error: unknown) {
  if (error instanceof Error) {
    logger.error(error.message);
  }
  else {
    logger.error(error);
  }
}
```
Then every catch block and other error messages would use that function

**Comment by boi123212321** [comment]
Branch: https://github.com/porn-vault/porn-vault/tree/logging

**Comment by boi123212321** [comment]
- [x] Setup Winston
- [x] Add logging config options
- [x] Add file logging
- [x] Add handleError function
- [x] Add plugin context $logger function
- [x] Added deprecation warning to $log
- [ ] Fully replace debug
- [ ] Update web UI /logs page
