### ISSUE TITLE
[Bug] Porn Vault isn't recognizing ".ts" videos

### ISSUE THREAD

**Issue by AssassinBleik** [porn-vault/porn-vault#1040]
**Describe the bug**

As mentioned in the title , porn vault will not recognize transfer stream ".ts" videos. 

**To Reproduce**

1- Set VIDEO_PATHS to folder containing ".ts" videos
2- start the program.

**Expected behavior**
All videos should be recognized and shown in the "scenes" page.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome
 - Version 24.4

**Comment by leadwolf** [comment]
PV only imports mp4 and webm at the moment. See related:
- https://github.com/porn-vault/porn-vault/issues/197
- https://github.com/porn-vault/porn-vault/wiki/Frequently-Asked-Questions#q-will-porn-vault-play-all-my-video-files
