### ISSUE TITLE
[Bug] Cannot upload an actor "alt thumbnail"

### ISSUE THREAD

**Issue by leadwolf** [porn-vault/porn-vault#1044]
> Having an issue setting actor images.
Cant seem to set a alt thumbnail image. Can pick a file, choose the cropping area but when I set the viewport just refreshes and does not set the image.  In the console you get the lines:
  vault:success File written to tmp/im_khwdkgazyspWZe85.jpg. +0ms
  vault:success Image processing done. +0ms
but it's not followed by "vault:success Image 'Actor Name (alt thumb)' done." line like it does for setting any other image.
When setting any of the other image types the viewport closes after cropping the image but it does not show the updated image in the 'change actor images' dialogue until after a refresh.

> Tried several different .jpg. The cropping window not closing and refreshing the image happens for all image types but a refresh of the browser window shows it has been added correctly (and the console also says that) apart from the alt thumbnail that does not set.

**Comment by boi123212321** [comment]
https://github.com/porn-vault/porn-vault/pull/1054
