### ISSUE TITLE
[Feature] Table/List view for Actors and Scenes

### ISSUE THREAD

**Issue by nickylass** [porn-vault/porn-vault#1052]
The card view we have at the moment when it comes to Actors and Scenes is great for regular view and navigation. But I have a great deal of data that I would love to see at once regarding each scene or actors. For instance, sometimes I would love to see the dates of all the scenes for a given actor sorted in a certain order. Or find those scenes that don't have a date set yet. I also keep scene IDs as a custom field and I would love to find those scenes missing an ID at a glance. 

For this reason, I would love to have a table/list view as an alternative to the cards for scenes and actors where each entry would be placed in this table, taking one row each and with all the available data as fields of the table. Maybe hovering over a part of the row would show the thumbnail of said scene. This would make it easier to see the dates or the missing fields in some actors and even to sort this table based on certain columns.

**Comment by echo6ix** [comment]
I think this is similar to ideas being discussed in #205

**Comment by leadwolf** [comment]
Indeed, viewing a lot of data is a prerequisite for editing it. Discussion will continue in #205
