### ISSUE TITLE
Allow deletion of scene images when mass deleting

### ISSUE THREAD

**Issue by leadwolf** [porn-vault/porn-vault#1058]
When deleting multiple scenes from the scenes page, there should be a checkbox to delete the scene's images. It is already done on a scene's details page.

**Comment by leonwright** [comment]
Hi! I'd like to take a look at this issue. Is this for when a scene is deleted from the filesystem or when the scene is deleted in the application itself?

**Comment by leadwolf** [comment]
When the scene is deleted from pvault

**Comment by boi123212321** [comment]
Shouldn't this happen already, looking at the `removeScenes` mutation?

**Comment by leadwolf** [comment]
My mistake, someone brought it up in discord, but I didn't realize they meant it's when selected multiple scenes in the scene list. In that case, there's no checkbox to delete images. Updating the issue
