### ISSUE TITLE
When a new tag is added to Performer, Movie, etc, apply tag to all previously associated Scenes

### ISSUE THREAD

**Issue by GernBlanston12** [porn-vault/porn-vault#1067]
Got frustrated the other day when I imported 166 videos into PV, and forgot to first give their corresponding Studio some applicable, common tags. It would be nice if, when a new tag is created for a Performer, Studio, Movie, etc. that all scenes currently associated to the element also inherit the new tag, even if they already exist in the db and are already associated. Often, I'll create a new performer after some number of scenes show up in the database; It would be nice if when I tagged that new Performer, the tag percolated down to her matching Scenes.

I feel like this would be a good holdover for some sort of mass-edit function, as the vast majority of tags to my videos are inherited from Performers, Studios, Etc.

Thanks!

**Comment by leadwolf** [comment]
For anyone who sees this later, this can be accomplished with the appropriate events configured for "applyActorLabels" and "applyStudioLabels"
