### ISSUE TITLE
Not all videos scanned

### ISSUE THREAD

**Issue by coanor** [porn-vault/porn-vault#1074]
**Describe the bug**
I got about 1000+ videos(all under the same dir, without sub-dirs), but each scan only scanned about 600+ videos. Is this a bug?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version:  PORN VAULT 0.25.0 READY

**Additional context**
Running porn-vault under MingW64 (installed via windows-git)

**Comment by boi123212321** [comment]
I'm guessing you're trying to import videos that are not .mp4 or .webm, which doesn't work currently

https://github.com/porn-vault/porn-vault/wiki/Frequently-Asked-Questions#q-will-porn-vault-play-all-my-video-files

It's an open issue though: https://github.com/porn-vault/porn-vault/issues/197
