### ISSUE TITLE
[Feature] Make labels assignable to a actor in a scene

### ISSUE THREAD

**Issue by pizzajohnny** [porn-vault/porn-vault#1075]
I thought it would be a cool idea if a Label could be assigned to an actor in a scene. The assigned labels could be then shown on the actors page. By clicking on it, all scenes of that actor and that label will be shown in the scene overview.

An example for assigned labels in scene view:
![example-scene](https://user-images.githubusercontent.com/61378413/101292010-19972c00-380d-11eb-8974-fe7468e7f858.png)

**Comment by boi123212321** [comment]
I don't think it's really feasible to introduce that into the current database schema, also it wouldn't really be searchable or anything, so I don't think it would really have any point to it
