### ISSUE TITLE
[Bug] stop in "vault:message Downloading latest Gianna (search engine) binary... +0ms"

### ISSUE THREAD

**Issue by duqingnian** [porn-vault/porn-vault#1079]
when i am run the porn-vault.exe on my windows10's powershell,the message stop in "vault:message Downloading latest Gianna (search engine) binary... +0ms"
![bug](https://user-images.githubusercontent.com/2705589/101355843-26318800-38d2-11eb-967b-97e0cacdea23.png)

**Comment by boi123212321** [comment]
This may be a powershell issue

Try downloading manually from: https://github.com/boi123212321/gianna/releases/download/0.2.2/gianna.exe and placing it next to the main exe

**Comment by duqingnian** [comment]
Fixed!Thinks a lot!
