### ISSUE TITLE
[Bug] "Play scene preview on mouse hover" breaks mouse wheel click UX

### ISSUE THREAD

**Issue by Timat123** [porn-vault/porn-vault#1082]
**Describe the bug**
If "Play scene preview on mouse hover" is enabled, mouse wheel clicking will open the scene in a new tab as expected, but the current tab will be in in autoscroll mode.

**To Reproduce**
1. Enable "Play scene preview on mouse hover"
2. Mouse wheel click on a scene
3. See error

**Expected behavior**
The scene opens in a new tab and the old tab is not in autoscroll mode.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: W10
 - Browser: Firefox
 - Version 83

**Comment by boi123212321** [comment]
Honestly, I don't know how to fix this, it seems to be a Firefox issue

**Comment by leadwolf** [comment]
fwiw I cannot reproduce in Firefox 83

**Comment by Timat123** [comment]
I can still reproduce this with a fresh firefox 87.0 and no plugins except ublock origin 🤔
