### ISSUE TITLE
[Bug] Results of studio's "find unmatched scenes" are only partially visible

### ISSUE THREAD

**Issue by Timat123** [porn-vault/porn-vault#1085]
**Describe the bug**
The amount of scenes in the UI increases to the new amount, but the new scenes are not displayed until I press F5

**To Reproduce**
1. "find unmatched scenes"
2. Observe

**Expected behavior**
The new scenes are being displayed

**Desktop (please complete the following information):**
 - OS: W10
 - Browser: Firefox
 - Version: 83

**Comment by boi123212321** [comment]
@leadwolf This is probably easy to fix by resetting the scene pagination...?

**Comment by leadwolf** [comment]
Probably. The list simply isn't updated right now I think
