### ISSUE TITLE
[Feature] Scene pagination should push the page to the history and urlbar

### ISSUE THREAD

**Issue by Timat123** [porn-vault/porn-vault#1087]
**Is your feature request related to a problem? Please describe.**
When going through all scenes to find untagged ones I can't continue my work after closing my browser.

**Describe the solution you'd like**
If I navigate to page foo, the history and urlbar should reflect that, and if I navigate to that url I should be on that page again.

**Comment by boi123212321** [comment]
Agreed, I wanted to add this a long time ago, but never got around to doing it
With 0.26 being a search overhaul, this could probably be added as well
