### ISSUE TITLE
Update Image when an image already exists in the library.

### ISSUE THREAD

**Issue by Ch00nassid** [porn-vault/porn-vault#1095]
**Is your feature request related to a problem? Please describe.**
this problem was identified when running the PICS plugin and it found a picture but failed to update the image for the actor.

Actor.ts:
```
      if (await Image.getImageByPath(path)) {
        logger.warn(`Image ${path} already exists in library`);
        return null;
      }
```

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/57732969/101775105-9c8de000-3ab4-11eb-9f81-eae14d4cc94f.png)

**Additional context**
As described in the Discord:
https://discord.com/channels/652499331265331245/759743481358450708/785983610623623218

**Comment by leadwolf** [comment]
Should be applied to all images handled by plugin events
