### ISSUE TITLE
[Bug] Studio detection ignores groupSeparators setting

### ISSUE THREAD

**Issue by Timat123** [porn-vault/porn-vault#1098]
**Describe the bug**
The `groupSeparators` setting works nicely for actor names, but apparently not for studio names.

**To Reproduce**
1. Have a `groupSeparators` regex that includes square brackets:
```json
"matcher": {
	"type": "word",
	"options": {
		"ignoreSingleNames": false,
		"ignoreDiacritics": true,
		"enableWordGroups": true,
		"wordSeparatorFallback": true,
		"camelCaseWordGroups": true,
		"overlappingMatchPreference": "longest",
		"groupSeparators": [
			"[\\s',()[\\]{}*\\.0-9_\\-+#']"
		],
		"wordSeparators": [
			"[-_]"
		],
		"filepathSeparators": [
			"[/\\\\&]"
		]
	}
}
```
2. Create a studio, e.g. SomeStudio
3. Create a file like "Some fancy title (SomeActor) [SomeStudio].mp4"
4. Restart pv, wait for the parsing to finish

**Expected behavior**
Pv detects that the scene belongs to SomeStudio, and sets its tag.

**Comment by leadwolf** [comment]
Can't reproduce with the same separators. Are you sure you don't have a studio "Some Studio" that is matched instead of "SomeStudio" ?

**Comment by Timat123** [comment]
Maybe I had a typo, I'll come back when I find the scene again!
