### ISSUE TITLE
[Feature] Make "Scenes" the default view when landing on a Studio page

### ISSUE THREAD

**Issue by GernBlanston12** [porn-vault/porn-vault#1148]
Just a minor thing, but I'd prefer, and I think others would as well, that when navigating to a given Studio page, Scenes is the default view/tab selected instead of Substudios. I very rarely navigate to a given Studio looking for substudios, 99.9% of the time, I'm looking to watch a Scene.

**Comment by leadwolf** [comment]
"Duplicate" of  #951.
@boi123212321 does the "maybe" label on this issue mean we should not simply change the default ? Having it be a user config (as suggested in the other issue) could be done separately

**Comment by boi123212321** [comment]
> "Duplicate" of #951.
> @boi123212321 does the "maybe" label on this issue mean we should not simply change the default ? Having it be a user config (as suggested in the other issue) could be done separately

I think having an option would be fine, but I'd keep the default as is.
