### ISSUE TITLE
[Feature] Page navigation at top of the page

### ISSUE THREAD

**Issue by GernBlanston12** [porn-vault/porn-vault#1149]
It would be nice if the page navigation at the bottom of the Actors listing was instead at the top, alongside the "actors found" header and "add actors" buttons. Why not have it at both the top and bottom? Navigating to the middle of a list of many stars (I have 1000+) is needlessly painful for having to scroll to the bottom of every page to move forward and having no tools to jump more than ~2 pages. It makes a daunting task of, say, iterating through a long list of added stars and editing any given aspect of each, as each edit resets the Actor listing to the top page of the list once you back out of the Actor's individual page, and you must then navigate, painfully, to the page you were on before to select the next actor. Imagine you have 40+ pages of actors, and have to scroll to the bottom of the page, press next page or forward button, an average of 20+ times each time you navigate to a given actor in the list as you move from one star to the next, or even to find a given single actor iteratively, and you'll get the picture.

**Comment by boi123212321** [comment]
Already implemented in the latest RCs
