### ISSUE TITLE
[Bug] Add Izzy and Gianna to Dockerfile

### ISSUE THREAD

**Issue by TushyAddicted** [porn-vault/porn-vault#1191]
Hello everyone, i tried running the provided Docker image but i noticed it has a major flaw, that i wasn't able to go around.
Izzy and Gianna are downloaded from their respective release pages and put in the root of the docker container (with volumes /images /videos /config and /config.json), but being the root a image layer the edits are not saved, the container reaches completion, reboots, doesn't find the needed binaries and loops over and over.

This should be easily solvable by ADDing the binaries in the Dockerfile of the image.

**Comment by leadwolf** [comment]
From 0.25 that shouldn't be the case, but there is a bug that is the root cause of this behavior: #1192

**Comment by TushyAddicted** [comment]
> From 0.25 that shouldn't be the case, but there is a bug that is the root cause of this behavior: #1192
> A potential workaround (for now) is that if you have the restart policy "unless-stopped", the files should be kept

Tried with 0.25.0 and 0.26.0-beta.4

Unfortunately it's not a vanilla docker setup, it's microk8s, a easy way to deploy a production ready k8s cluster and the lifecycle of a pod is a little different so the restart policy wouldn't work. In this particular deployment it's not even running docker under the hood but containerd.

Had a look at the `/proc/self/cgroup` file and the docker string is missing, i could only notice the strings `kubepods` and `snap.microk8s.daemon-containerd.service`

`/ # cat /proc/self/cgroup
11:freezer:/kubepods/besteffort/podf9e58c5f-dfd0-4c5d-b8ae-756b3565a298/983fab2a0cda8b61ab1c7293ca93286ce1ddfbecd158bcfd530be1adbf0b432d
10:cpuset:/kubepods/besteffort/podf9e58c5f-dfd0-4c5d-b8ae-756b3565a298/983fab2a0cda8b61ab1c7293ca93286ce1ddfbecd158bcfd530be1adbf0b432d
9:pids:/kubepods/besteffort/podf9e58c5f-dfd0-4c5d-b8ae-756b3565a298/983fab2a0cda8b61ab1c7293ca93286ce1ddfbecd158bcfd530be1adbf0b432d
8:devices:/kubepods/besteffort/podf9e58c5f-dfd0-4c5d-b8ae-756b3565a298/983fab2a0cda8b61ab1c7293ca93286ce1ddfbecd158bcfd530be1adbf0b432d
7:net_cls,net_prio:/kubepods/besteffort/podf9e58c5f-dfd0-4c5d-b8ae-756b3565a298/983fab2a0cda8b61ab1c7293ca93286ce1ddfbecd158bcfd530be1adbf0b432d
6:cpu,cpuacct:/kubepods/besteffort/podf9e58c5f-dfd0-4c5d-b8ae-756b3565a298/983fab2a0cda8b61ab1c7293ca93286ce1ddfbecd158bcfd530be1adbf0b432d
5:hugetlb:/kubepods/besteffort/podf9e58c5f-dfd0-4c5d-b8ae-756b3565a298/983fab2a0cda8b61ab1c7293ca93286ce1ddfbecd158bcfd530be1adbf0b432d
4:blkio:/kubepods/besteffort/podf9e58c5f-dfd0-4c5d-b8ae-756b3565a298/983fab2a0cda8b61ab1c7293ca93286ce1ddfbecd158bcfd530be1adbf0b432d
3:perf_event:/kubepods/besteffort/podf9e58c5f-dfd0-4c5d-b8ae-756b3565a298/983fab2a0cda8b61ab1c7293ca93286ce1ddfbecd158bcfd530be1adbf0b432d
2:memory:/kubepods/besteffort/podf9e58c5f-dfd0-4c5d-b8ae-756b3565a298/983fab2a0cda8b61ab1c7293ca93286ce1ddfbecd158bcfd530be1adbf0b432d
1:name=systemd:/kubepods/besteffort/podf9e58c5f-dfd0-4c5d-b8ae-756b3565a298/983fab2a0cda8b61ab1c7293ca93286ce1ddfbecd158bcfd530be1adbf0b432d
0::/system.slice/snap.microk8s.daemon-containerd.service`

Would it be possibile to use `kubepods` as well as `docker` during the container detection?

**Comment by TushyAddicted** [comment]
#1193

**Comment by TushyAddicted** [comment]
#1193 Submitted a pull request

**Comment by leadwolf** [comment]
If you want to build the container from source, you can do that. But a better idea is to just avoid container detection in the first place. I'm thinking of using an environment variable which will contain the path to the config folder ("." in normal use, "/config" in a container). That way we can just add that environment variable in the Dockerfile.

**Comment by TushyAddicted** [comment]
> If you want to build the container from source, you can do that. The problem is some users report not having anything in the file at all.
> A better idea is to just avoid container detection in the first place. I'm thinking of using an environment variable which will contain the path to the config folder ("." in normal use, "/config" in a container). That way we can just add that environment variable in the Dockerfile.

Sounds awesome, even more versatile
