### ISSUE TITLE
Format video filename

### ISSUE THREAD

**Issue by boi123212321** [porn-vault/porn-vault#1204]
Reverse case of https://github.com/porn-vault/porn-vault/issues/367
Currently the only way to change a filename is to change in the database. With https://github.com/porn-vault/porn-vault/issues/367, it could be changed in the Web UI.
Instead of selecting a new file name manually, rename the existing file to match some kind of pattern.
The pattern can be filled with info stored in PV, example:

Some random video file named `abcdef.mp4` could be renamed into `Blake Blossom - Blake's Boobs Blossom (HardX, 2021-01-29).mp4`, using this pattern (arbitrary format):
```{ actors } - { scene title } ({ studio name }, { date_yyyymmdd })```

with scene info (info from PV, pseudo info as example):
```
{
  name: "Blake's Boobs Blossom",
  studio_name: "HardX",
  actors: ["Blake Blossom"],
  date: " 2021-01-29"
}
```

This could be done via button action in the scene details, automatically updating the scene document.

It's important PV checks the length of the new filename because most OSes limit the filename (Windows = ~255 chars)

**Comment by boi123212321** [comment]
Setting delimiter for arrays could be achieved using a second argument (thanks @leadwolf ):

```
{{ actors, "&" }}
```

**Comment by arcadianCdr** [comment]
Shouldn't we just modify plugins so they have the ability to update the scenePath? Then we could have renamers, organizers,... plugins that could go much further (reorganizing folders, rename or copy,...). Seems much more flexible...

**Comment by boi123212321** [comment]
> Shouldn't we just modify plugins so they have the ability to update the scenePath? Then we could have renamers, organizers,... plugins that could go much further (reorganizing folders, rename or copy,...). Seems much more flexible...

Plugins already had the ability to update the scene path, but I just pushed another commit so there are some checks done and metadata reloaded. I haven't really thought of using plugins for some reason..
