### ISSUE TITLE
[Feature] Customize video jump time 

### ISSUE THREAD

**Issue by coanor** [porn-vault/porn-vault#1235]
**Is your feature request related to a problem? Please describe.**
The seeking step can be customized in `config.json`. Current default to 5s.

**Comment by boi123212321** [comment]
I'm not sure I understand what you mean by `ffmpeg seek time`... the screenshot interval can be set in the config.json

**Comment by coanor** [comment]
> I'm not sure I understand what you mean by `ffmpeg seek time`... the screenshot interval can be set in the config

When playing video, the default step is 5 second.

**Comment by boi123212321** [comment]
Ah right that's not ffmpeg though

**Comment by leadwolf** [comment]
Customization in #927
Setting the values in config.json will be in #456
