### ISSUE TITLE
[Feature] Implement speed and resizing control to video player

### ISSUE THREAD

**Issue by Red5ive-UK** [porn-vault/porn-vault#1260]
**Describe the solution you'd like**
Implement speed controls for the video player for slow-mo and fast forward.

SpankBang have a good setup with button to select predefined speeds such as 0.5x, 1x, 1.5x, 2x etc (see screenshot)
![Untitled](https://user-images.githubusercontent.com/56472650/108836786-2edc5500-75c9-11eb-9b6b-e8cb1806645e.jpg)

Would be great to have the window resizable as well, like in issue 828 but something that is selectable such as double size, fill to window, full screen.

**Comment by leadwolf** [comment]
Playback rate in #1254

For size options:
> How about a size like "theater" on youtube, where the player takes the full width of the screen. The markers can move under the player in this mode, just like they already do on a smaller screen

**Comment by Red5ive-UK** [comment]
> How about a size like "theater" on youtube, where the player takes the full width of the screen. The markers can move under the player in this mode, just like they already do on a smaller screen

Yeah, that sounds a great solution. Enlarges the video but still retaining the marker functionality for a nice mid-point between standard and full screen.

**Comment by blahblahthrowaway** [comment]
A couple additional features:

- Referencing to spankbang player or youtube, is the tapping on either side of the video to advance forward or backward.  The current player just pauses/unpauses on tap.
- Optimize the seek bar for mobile, on a tablet/phone it is very difficult to 'scrobble' and move the position of the video.  This is exacerbated by the above behavior of every tap triggering a pause/unpause

**Comment by leadwolf** [comment]
Updated #1254 :
- Added rudimentary double tap seeking
- Various touch improvements
