### ISSUE TITLE
[Feature] Transcoding / Added Video Support

### ISSUE THREAD

**Issue by blahblahthrowaway** [porn-vault/porn-vault#1271]
**Is your feature request related to a problem? Please describe.**
There are currently limited file/codec/containers supported.  Additionally, for some higher resolution formats those can tax the endpoint and potentially be unplayable.

**Describe the solution you'd like**
Provide a transcoding option to allow for greater codec/container support.  Additionally, would allow to offload the processing of larger files to a server to transcode to a more palatable format for the endpoints (phone, tablet etc)

**Additional context**
Not a trivial ask, but immensely helpful for collections with different codecs/containers.  Something like Plex etc being a gold standard, but any ffmpeg implementation would be a helpful addition.

**Comment by boi123212321** [comment]
https://github.com/porn-vault/porn-vault/issues/197

**Comment by leadwolf** [comment]
Closed for duplicate
