### ISSUE TITLE
[Bug] Navigation Bar Disappears

### ISSUE THREAD

**Issue by blahblahthrowaway** [porn-vault/porn-vault#1274]
**Describe the bug**
Periodically the top navigation bar disappears while browing items.

**To Reproduce**
Not positive on specific steps, but have noticed while paginating through lists of Actors and then periodically opening an Actor, running scripts, and then going 'back' to the prior page.  At some indeterminate point the top nav bar disappears.

**Expected behavior**
Nav bar should not be disappears

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ChromeOS
 - Browser Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by arcadianCdr** [comment]
I have that a lot as well. I'll try to capture a sequence to reproduce consistently.

**Comment by ShadowWalker99** [comment]
@arcadianCdr the sequence is, go to a scene, scroll down until the top nav bar is hidden, then click the "return" arrow next to the title. Then the top nav bar will stay hidden.

**Comment by leadwolf** [comment]
Seems to be a bug in Vuetify: https://github.com/vuetifyjs/vuetify/issues/12505
Should we implement the "hack" mentioned there ?

**Comment by boi123212321** [comment]
> Seems to be a bug in Vuetify: [vuetifyjs/vuetify#12505](https://github.com/vuetifyjs/vuetify/issues/12505)
> Should we implement the "hack" mentioned there ?

I'd say so, yeah, doesn't look like it has any drawbacks
