### ISSUE TITLE
*Bug* Movie page layout gets messed up when adding cover images on desktop

### ISSUE THREAD

**Issue by Red5ive-UK** [porn-vault/porn-vault#1280]
**Describe the bug**
On the movie details page the layout gets broken after adding a spine image as well as the covers.
The results are that the two cover images don't align with each other when hovering over them to display and the description text is showing over the graphic elements.
When adding a studio the logo takes a lot of real estate up at the top and pushes everything down the screen.

![1 (1)](https://user-images.githubusercontent.com/56472650/109856492-73af5e00-7c51-11eb-8eb4-ece49b7faece.jpg)

![3](https://user-images.githubusercontent.com/56472650/109856559-87f35b00-7c51-11eb-8b0d-0b47b449c4bb.jpg)

 - OS: Windows 10
 - Browser: Chrome / Edge Chromium
Did not test on mobile

A simple fix might be to not show the spine image at all on this page as it's only relevant for the 3D cover view, talking of which,  it would be great to have the 3d view embedded on the main page as an option rather than in a separate screen, like this website (though with the full box view): [https://erotik.com/en/magma-film/immergeile-muttis]
At the very least having the 3D mode remember the box colour you selected rather than reset to black on exit would be helpful.

**Comment by leadwolf** [comment]
@Red5ive-UK 
#1370 will remove the spiner cover from the main view and save the box color.
I suggest creating a separate feature request to directly embed the 3D viewer

**Comment by Red5ive-UK** [comment]
Cheers leadwolf! I'll put in a separate request for the 3D viewer
