### ISSUE TITLE
[Bug] Sorting alphabetically gives an error in the app

### ISSUE THREAD

**Issue by arcadianCdr** [porn-vault/porn-vault#1281]
**Describe the bug**
pv 0.26.0. A collection of 266 actors: sort alphabetically/ascending. No other filters.

**To Reproduce**
Click refresh.

**Screenshots**
<img width="968" alt="image" src="https://user-images.githubusercontent.com/77160044/109930512-068adf80-7cc8-11eb-9742-87dab6b5922d.png">

Not a lot to report on the server:

```
2021-03-04T07:54:42.063Z [vault] debug: Auth OK
2021-03-04T07:54:42.064Z [vault] verbose: Searching "pv-actors" for "<no query>"...
```

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Browser Firefox

**Comment by boi123212321** [comment]
--reindex to rebuild search index, the A-Z sort was added in some beta version, so older search indices don't have that, and so it errors
