### ISSUE TITLE
[Feature] Scenes Upload Button

### ISSUE THREAD

**Issue by Connor2397** [porn-vault/porn-vault#1283]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when you go into Scenes and are unable to upload videos.

**Describe the solution you'd like**
Like you have on the Images page you can click the upload button to upload files.

Current Version: leadwolf/porn-vault:0.25.0-alpine

**Additional context**
Current Layout
![image](https://user-images.githubusercontent.com/17101541/110026068-163a1080-7d28-11eb-8b38-4aa8db33c461.png)

Future Layout
![image](https://user-images.githubusercontent.com/17101541/110026612-c0b23380-7d28-11eb-9643-152186dc990a.png)

**Comment by boi123212321** [comment]
Because uploading something copies it, it would copy gigabytes of data so it doesn't really seem like there's a point for uploading scenes. That's why they're added by scanning folders only.
