### ISSUE TITLE
[Feature] Bulk remove deleted files

### ISSUE THREAD

**Issue by Timat123** [porn-vault/porn-vault#1366]
**Is your feature request related to a problem? Please describe.**
I have renamed a bunch of folders, now there are many duplicate entries, and the old ones don't work any more because the file is no longer at the old location.

**Describe the solution you'd like**
A "check if all files are still present and ask whether the scenes should be deleted" button would be nice

**Comment by leadwolf** [comment]
Duplicate of #320 although I will copy your concerns

**Comment by Timat123** [comment]
Your link to #320 404s, are there any news?
