### ISSUE TITLE
[Feature] PV should warn about files in unsupported formats

### ISSUE THREAD

**Issue by Timat123** [porn-vault/porn-vault#1367]
**Is your feature request related to a problem? Please describe.**
Right now there is no nice way to find all unsupported files

**Describe the solution you'd like**
PV should warn for each unsupported file on startup until #197 is solved

**Additional context**

**Comment by leadwolf** [comment]
I don't think this is necessary. The fact that only mp4 and webm are supported is in the faq, most people in the discord can answer to that question if ever it comes up in the discord.  
#197 shouldn't be too far off as well

**Comment by Timat123** [comment]
This does not one to get a list of all files one has to convert though :)

**Comment by leadwolf** [comment]
That can easily be accomplished with external tools. Example in bash: `find . -not -name "*.mp4" -not -name "*.webm"`

**Comment by Timat123** [comment]
Sure, but everytime I do that I'd have to check what you are currently supporting :P
