### ISSUE TITLE
[Bug] (0.27rc) 'createMissingLabels' option not honored, duplicate labels are being created by plugins.

### ISSUE THREAD

**Issue by KingWizard1** [porn-vault/porn-vault#1442]
**Describe the bug**
Duplicate labels are created when adding an actor that invokes the Freeones plugin (if installed). Imported labels aren't checked against existing labels or their aliases resulting in duplicates being created.

**To Reproduce**
We will use `Remy LaCroix` as our example actor to reproduce the issue.
1. Install the Freeones plugin from the `0.27.0` plugins branch with default config settings.
2. Register the Freeones plugin to the `actorCreated` event.
3. Check that the `plugins.createMissingLabels` setting is set to `true`.
4. Check that the `matching.applyActorLabels` setting contains the value `event:actor:create`.
5. Run PV and check that the following labels exist in the database (for Remy): `Female, Brunette, Hazel Eyes`
6. Add `Remy LaCroix` as an actor. Remy's labels on Freeones should be as in Step 5.
7. Labels returned from Freeones are not checked against existing labels, resulting in duplicate labels being created and assigned to the actor instead of the existing ones.

**Expected behavior**
Labels being imported should be checked against existing labels and their aliases. If the label or label alias exists, the -existing- label should be attached to the actor. If not, a new label should be created and be attached.

**Screenshots**
A screenshot of my Labels page showing duplicates that got added after adding actors in `Bulk`. You can see the existing one is the one with a color associated with it. All others are new duplicates.
https://imgur.com/a/KatVumD

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This problem is not present in 0.26.0.

**Comment by boi123212321** [comment]
Set the log level to debug or silly (maybe using a file logger) and copy that log

In log.writeFile add:
```
{
  "level": "silly",
  "prefix": "silly-",
  "silent": false
}
```

**Comment by KingWizard1** [comment]
Okay I have narrowed this down to the `matching.matcher.options.ignoreSingleNames` setting.

If this is set to `true`, then duplicate labels get created. If false, the labels are matched correctly and duplicates are not created (as desired).

**Comment by boi123212321** [comment]
Intended behavior then, but in the future labels may use a fixed matcher
