### ISSUE TITLE
Scrolling warning message

### ISSUE THREAD

**Issue by theebadone** [porn-vault/porn-vault#1532]
I just started using this, and so far so good. I have added my library, added actresses, and even added labels. The problem is when I go to close the porn-vault program, I noticed a scrolling warning:

![image](https://user-images.githubusercontent.com/85198245/120390968-62cbc280-c2fc-11eb-8b27-0734138f12cb.png)

Any help with this would be much appreciated!

**Comment by leadwolf** [comment]
Try reindexing. Then see if still get the errors. If you do, but don't notice any problems you can ignore it.
