### ISSUE TITLE
[Feature] <File-name management>

### ISSUE THREAD

**Issue by dnizmirc** [porn-vault/porn-vault#1538]
**Is your feature request related to a problem? Please describe.**
I'm sorting through a lot of stuff saved over a decade+. A lot of unhelpful filenames, stuff is just tossed in folders. PV currently doesn't rename files, and if I rename them myself, it winds up creating a new extra scene and leaving a dead-entry to the now "missing" scene. I get that some might not want PV to automatically drop missing content, because of NAS' and stuff, makes sense.

**Describe the solution you'd like**
I'd like an option to push the titles I give in PV to the actual file-names. This could limit PV titles to character limitations windows has, and I'd be fine with that, but others might not. A prompt for me to fix the title if it can't output that, or for PV to automatically drop characters it can't use would be great, too. Besides just cleaning up my own physical directories with correct information, it'd also help with some redundancy. If PV's database goes up, a lot of my work would be mirrored to the actual filenames.

I'd like if I could move files among directories, too. It would let me reorganize my stuff without creating dead-entries/duplicates, but that might be a separate feature request itself.

**Comment by boi123212321** [comment]
Most can already be achieved through plugins: https://github.com/porn-vault/plugins/tree/0.27/plugins/fileorganizer
