### ISSUE TITLE
[Bug] 'maxMemoryUsageInMB limit exceeded' on certain high resolution images

### ISSUE THREAD

**Issue by superluigi3** [porn-vault/porn-vault#1550]
**Describe the bug**
Some high resolution JPEG images  cannot be added and the following error is presented:
`2021-06-14T18:01:44.464Z [vault] error: maxMemoryUsageInMB limit exceeded by at least 34MB`
`2021-06-14T18:01:44.469Z [vault] error: Failed to add image`

**To Reproduce**
1. Start scan on high resolution images

**Expected behavior**
Images should get processed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - PV Version: 0.27.0

**Additional context**
- The amount of memory can be either a few MBs or over a hundred.
- All problematic images have a resolution between 4480 x 6720 and 10328 x 7760, however some in-between values are processed correctely. 
- File sizes never exceed ~5MB.
- It could be related to a **JIMP bug** https://github.com/oliver-moran/jimp/issues/915

**Comment by boi123212321** [comment]
https://github.com/porn-vault/porn-vault/issues/1237
