### ISSUE TITLE
[Feature] <Return to area selected>

### ISSUE THREAD

**Issue by dnizmirc** [porn-vault/porn-vault#1554]
**Is your feature request related to a problem? Please describe.**
I find myself on a Performer's page, I click into a scene to update some info, which might be as simple as editing a title. I then either hit backspace or click the back arrow, but it brings me back to the Metadata tab of the Performer. I then need to click onto the Scenes tab again. Occasionally, a performer has more scenes than displayed by default, and if I'm going through the list, I now also need to click Load More (possibly several times, depending on how many they have). It's just frequent extra annoyances I'd like to minimize, if it were possible. 

**Describe the solution you'd like**
If I backspace, or click the back-arrow (or just one of the two), I'd like to go back to exactly what I was looking at before I clicked into a scene/movie.

**Additional context**
Personally, I wouldn't mind being able to reorder the tabs on a performer's page. That would also solve the problem. Once I have the performer set up, I generally don't need to see/edit their metadata sections. The Scenes tab is really what I'm going to be interacting with 99% of the time. But that might be a separate request...

**Comment by boi123212321** [comment]
I think it's best for you to start using your middle mouse button to open stuff in a new tab.
Obviously it's possible to cache page states so if you return it's exact same as you left it, but that also has downsides like stale data.
There's no need to add extra complexity for this when any browser can handle it just fine.
