### ISSUE TITLE
[Feature] Read and Write NFO files (XML METADATA)

### ISSUE THREAD

**Issue by Lokotito** [porn-vault/porn-vault#1562]
.NFO files (ex. Kodi format) are used to store locally information about media (episodes, scenes or movies), in practice store METADATA with useful information like Title, Plot, Genre, Studio, Actors... in  XML format (basically a text document).
https://kodi.wiki/view/NFO_files

This is especially useful for OFFLINE work, when the multimedia files are backed up to another storage medium and then later can be accessed again on the main storage. 
Will be very useful export/write all DATA generated in Porn-Vault ONLINE (in same media file directory), and later can be load/read this .NFO metadata to be shown in Porn-Vault WEB-UI.

**Comment by boi123212321** [comment]
https://github.com/porn-vault/plugins/issues/174
