### ISSUE TITLE
[Feature] Disable/Toggle option to automatically apply performer tags to videos.

### ISSUE THREAD

**Issue by dnizmirc** [porn-vault/porn-vault#1571]
**Is your feature request related to a problem? Please describe.**
I tag performers (Acceptable) after I've verified all their information and I think they're in an acceptable state, so that I can filter them out later when looking for performers I need to update. I use the same tag for videos (Acceptable) once I'm happy with them. When a a new video is added, if it detects a performer, it assigns them and their tags to that video. So, videos that I've not checked are getting tagged incorrectly. 

I suspect an immediate suggestion would be for me to use separate tags. That would work. Except I can't mass-edit video or performer's tags, yet, so I don't have any way to quickly change that tag on 2000+ Scenes or 700+ Performers. Also, the tag *means* the same thing, and I'd really not have to start worrying about what tags I need to have Performer and Scene versions of. Just seems overly complicated and adds more stuff to add to the Labels list.

I'm not looking to change the functionality for everyone else, but the option to disable that would be appreciated.

**Describe the solution you'd like**
Just want to be flag a setting to disable automatically applying Actor tags to Scenes.

**Comment by boi123212321** [comment]
Adjust matching.applyActorLabels in config (maybe just empty it):

JSON
```json
"applyActorLabels": []
```

YAML
```yaml
applyActorLabels: []
```
