### ISSUE TITLE
ElastiSearch Requirement Not Listed

### ISSUE THREAD

**Issue by LeeThompson** [porn-vault/porn-vault#1585]
Tried this out on docker only to have it suddenly stop almost immediately twice (once to download something and the other because it couldn't connect to ElastiSearch, whatever that is.)

You should probably include this requirement in the docker registry description and your readme here.

**Comment by boi123212321** [comment]
ElastiCsearch is both mentioned in the getting started guide (https://porn-vault.github.io/porn-vault/guides/getting-started.html) and the docker guide (https://porn-vault.github.io/porn-vault/guides/docker.html#docker-compose).

**Comment by LeeThompson** [comment]
Thanks but FYI it did not point me to any of that from the docker hub registry.
