### ISSUE TITLE
[Feature] Login Page

### ISSUE THREAD

**Issue by virusperfect** [porn-vault/porn-vault#1635]
**Is your feature request related to a problem? Please describe.**
Would it be possible to add a login page? That way I don't have to rely on nginx (I don't want to expose my whole porn library to the internet without authentication).

**Describe the solution you'd like**
A simple login page (it really doesn't have to be anything fancy).

**Additional context**

**Comment by boi123212321** [comment]
Use password in config

**Comment by virusperfect** [comment]
Thanks
