### ISSUE TITLE
[Feature] Improve the search feature

### ISSUE THREAD

**Issue by ghost** [porn-vault/porn-vault#222]
- Make "Fuzzy search" a UI checkbox option so it can be enabled/disabled similar to "Favorites" etc.
- Support boolean search features such as **and, or, not, parentheses**
- Support the ability to search in specific fields, e.g. search for "Anna" in the actor's name, or "Vacation" in the filename / title, etc. This can be implemented in the search query, or have a separate "Actor filter" and leave the "Search query" to search in the title/filename/path.

- Support the ability to save such search criteria as "Saved searches".

**Comment by echo6ix** [comment]
Can we consider a way to do this without adding more clutter to the UI with check boxes?

Maybe have the end-user access the extended search functionality through the use of quotation marks, ticks, brackets, or braces?

None fuzzy searches can be surrounded by tick marks?
- \`non fuzzy search`

Literal searches can be surrounded by quotation marks?
- `"literal search"`

Searches containing operators and parameters (specific fields) can be surrounded by brackets or braces? And parameters (specific fields) can be called using a delimiter, like the `$`.
- `($actor:jane & $age:>30)`
