### ISSUE TITLE
[Feature] Support text files

### ISSUE THREAD

**Issue by iamjen023** [porn-vault/porn-vault#309]
i like to see the support of txt files and a way to input new text (stories)

this would work by
clicking new story will take you to a page for importing text copy and paste it in then click save
when it saves it would create a simple .txt

.txt files
when the scan see a new .txt file then it will add them auto by scanning

a sample if a txt file for some add functionality

story.txt

`
%% comment will not display after this tell next line

%author%=the author %% will apply to metadata in app

%site%=site.com %%where the story come from

%storyurl%=https://site.com/story.html %% click able to see story post

%tiltle%=name of story %% will apply to metadata in app

%description%= this si a description of the story %% this applys to story page under title

%start% %% says the start of the story

%part%=1 %% for next part this be for series to go the next part with out going back to stories page could be 1 to ∞

%end% %%this test app the end of the story

**Comment by echo6ix** [comment]
Yeah, I have a folder with a few `TXT` files and `PDF` files. Scanning a designated `Stories` folder would work for me.

This is a good paradigm of how to present the section: [https://xhamster.com/stories](https://xhamster.com/stories). Another good paradigm is using the same display as the Scenes page, and letting the end-user select a thumbnail from their library as cover art for each Story.

Also ability to add labels to the story.
