### ISSUE TITLE
Replace video file

### ISSUE THREAD

**Issue by GernBlanston12** [porn-vault/porn-vault#367]
Upon deletion or discovery of a missing file, add a mechanism for user to select a video file replacement. Upon selection of an alternate video file, the original file's tag associations, associated performers, etc are transferred to the new file. This would allow user to designate a new, higher-resolution version of the same scene, for example, to replace the old copy without having to re-work bookmarks, etc.  As an added layer, if you ever did incorporate perceptual hashing for dupes, you could work it in this context to confirm the files match perceptually before transferring tag associations to the new file.

**Comment by boi123212321** [comment]
https://github.com/porn-vault/porn-vault/pull/1206
