### ISSUE TITLE
Folder Navigation For Images

### ISSUE THREAD

**Issue by GernBlanston12** [porn-vault/porn-vault#368]
When any given video can have dozens of associated preview images, vendor screenshots, pictorial images of the scene and even separate associated photoshoots with the actress, having different ways to aggregate images within TPM becomes important to users with large collections. Having access to aggregation by directory within TPM, along with the in-development mass tagging options, would add another tool for users like myself who have larger collections and need ways to rapidly aggregate videos and images for the purpose of database associations, tagging, etc.  Users are likely to come upon TPM having large collections of images in various named directories, and those folder names/associations are metadata to be quickly translated into associations in TPM. Adding folder navigation in TPM for images would go beyond the current auto-tagging features and allow users to form associations in the db quickly without having, for example, the exact name of the associated scene in the path for the given pictorial image directory. Users may have, as another example, packs of images from Freeones and the like that are associated to a given video in their collection, but not named in any discernible way for the auto-tagger to take advantage of. Having a way to navigate folders in TPM would make these associations easier where manual control over tag associations is called for, but often necessary for many images at a time.

**Comment by Red5ive-UK** [comment]
Agree with this.
Especially about not having to rename every image with the full actor and scene name for it to be tagged correctly to the scene and actor. If it can support folder import and all the images in it are the tagged with the details in the folder name then that would save a lot of admin work.

**Comment by natcoso9955** [comment]
Would also be good to be able to create folders in the images section, For those of us who have already got an 8000+ image collection and it's not in folders, this would be good. 😄

**Comment by boi123212321** [comment]
There will be image galleries, but having folders defeats the purpose of the entire program, I wanted to eliminate the need to have folder diving. Fully modelling a file system is simply not easy to integrate into the current code base.

@Red5ive-UK Image info is extracted from the full path so that already works https://github.com/porn-vault/porn-vault/blob/dev/src/queue/check.ts#L69
