### ISSUE TITLE
[Bug] Multiple labels are applied when label contains another label

### ISSUE THREAD

**Issue by pizzajohnny** [porn-vault/porn-vault#401]
I noticed a bug while experimenting with plugins.
When a labels contains another label, both labels are applied to the actor.
Example: `Male` and `Female` label on actors. Tested on version `0.15.0-rc.4`.

![labels](https://user-images.githubusercontent.com/61378413/76652566-22e9b580-6567-11ea-9edc-af15727d845b.gif)

**Comment by Ch00nassid** [comment]
this applies to new scenes that are added to a collection.  I noticed that i added a new scene that was missing from a movie i had:
The scene had "Part 10" and when I added it to my scene collection, it automatically added the "art" label to the scene (which isn't wrong really...but... it was p**art** of another full word?).

Anyways, it will be nice to have this corrected :)

**Comment by boi123212321** [comment]
maybe add a "negative" alias that prohibits another label?
like:
```json
[{
  name: "female",
  aliases: [
    "girl",
    "~male"
  ]
},
{
  name: "male"
}
]
```

what do you think? @pizzajohnny

**Comment by pizzajohnny** [comment]
I guess that would be a good solution for tags like `Female` and `Male`. Unfortunately I have no solution idea for the other Ch00nassid mentioned.

**Comment by h1z1** [comment]
Can confirm this.  There's some really weird behavour with labels in general..  adding one sometimes randomly gets applied to everything.  No idea what is going on there.

**Comment by boi123212321** [comment]
@h1z1 Because the matcher is substring based and not really smart it tends to do some unexpected matches sometimes.
@leadwolf is making a smarter matcher that should help with that and close this issue
