### ISSUE TITLE
[Feature] UI: Avatar and hero image for studios

### ISSUE THREAD

**Issue by echo6ix** [porn-vault/porn-vault#413]
Ability to add a 1:1 avatar and a hero image to studios similar to the actors page.

And possibly display them together like this when displaying a list of all studios?

![Annotation 2020-03-18 232152](https://user-images.githubusercontent.com/37937507/77028576-82810000-696f-11ea-80c9-f9d459d30aae.jpg)

Avatars would be easy to obtain as many studios already provide a 1:1 avatar on streaming platforms and their twitter profiles.

**Comment by boi123212321** [comment]
https://github.com/porn-vault/porn-vault/issues/1117 Studio hero images won't happen i think
