### ISSUE TITLE
[Feature] rename download files sensibly

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [porn-vault/porn-vault#500]
Looking in Releases, filenames are completely non-descriptive. If I were to download and then not look at the file for a week, I would have no idea what it is. Please include program-name or some other descriptive in the archive name.

**Edit:** Yes, I realize I can change the filename prior to actually starting the download. I think it's safe to say that almost nobody ever does that in real life. Changing the default filename is super easy.

**Comment by Ch00nassid** [comment]
I think i would like something like this but I think everyone would have their own standard on the naming convention.  Maybe a setting?  not sure, the scope of this might snowball out of control a bit.

**Comment by ParaplegicRacehorse** [comment]
Uh... Perhaps you misunderstand. @boi123212321 has created a software product and provides download links on the Releases page. Currently, those files are called 'Linux.zip', 'Windows.zip' (the most recent contains the version number.)

The problem with this is, sitting in my Downloads folder is now a file with the name `Linux.zip` and I have **__no idea__** what it is. The filename provides nothing useful in determining the origin or nature of the contents. Filename `Linux-0.20.zip` is not of any additional use in identifying the nature or source of the file.

`PornVault-Linux-0.20.zip` -- Now, THAT tells me what the file is; or gives a useful jog to my memory.

**Comment by boi123212321** [comment]
Problem is the files & zips are created by a Github Action and the build scripts aren't that easy to edit and test, if anyone can improve that, that'd be cool
https://github.com/boi123212321/porn-vault/blob/dev/.github/workflows/release.yml
https://github.com/boi123212321/porn-vault/blob/dev/package.json

**Comment by ParaplegicRacehorse** [comment]
> Problem is the files & zips are created by a Github Action and the build scripts aren't that easy to edit and test, if anyone can improve that, that'd be cool
> https://github.com/boi123212321/porn-vault/blob/dev/package.json

I am going guess that the relevant lines to edit are these (lines 19-27):
```
"build:armv7": "mkdir -p releases/armv7/app/dist && pkg . --out-path ./releases/armv7 --targets node10-linux-armv7 --options max_old_space_size=8192 && cp -r ./views ./releases/armv7 && cp -r ./assets ./releases/armv7 && cp -r ./app/dist ./releases/armv7/app && npm run zip:armv7",
"build:linux": "mkdir -p releases/linux/app/dist && pkg . --out-path ./releases/linux --targets node8-linux-x64 --options max_old_space_size=8192 && cp -r ./views ./releases/linux && cp -r ./assets ./releases/linux && cp -r ./app/dist ./releases/linux/app && npm run zip:linux",
"build:win": "mkdir -p releases/win/app/dist && pkg . --out-path ./releases/win --targets node8-win-x64 --options max_old_space_size=8192 && cp -r ./views ./releases/win && cp -r ./assets ./releases/win &&  cp -r ./app/dist ./releases/win/app && npm run zip:win",
"build:mac": "mkdir -p releases/mac/app/dist && pkg . --out-path ./releases/mac --targets node8-macos-x64 --options max_old_space_size=8192 && cp -r ./views ./releases/mac && cp -r ./assets ./releases/mac &&  cp -r ./app/dist ./releases/mac/app && npm run zip:mac",
"zip:armv7": "zip -r ./releases/armv7.zip ./releases/armv7",
"zip:linux": "zip -r ./releases/linux.zip ./releases/linux",
"zip:win": "zip -r ./releases/win.zip ./releases/win",
"zip:mac": "zip -r ./releases/mac.zip ./releases/mac"
```

> https://github.com/boi123212321/porn-vault/blob/dev/.github/workflows/release.yml

and in this file, these (lines 27-29) :
```
          releases/mac.zip
          releases/linux.zip
          releases/win.zip
```

Presumably, both of these config files can set the filename with a variable = to the release-tag-name/number.

For example, package.yml might declare the filenames as `releases/mac${{ releases.tagname }}.zip` or similar.

**Comment by ParaplegicRacehorse** [comment]
Bump.

I see that [PR #790](https://github.com/boi123212321/porn-vault/pull/790) may be a fix. Please test and merge.
