### ISSUE TITLE
[Feature] Settings page layout: Reorganize, restructure, material design-ify

### ISSUE THREAD

**Issue by echo6ix** [porn-vault/porn-vault#524]
**Is your feature request related to a problem? Please describe.**
The settings page currently doesn't have a lot going on, but I'm sure more options will be added to it in the future. As it stands the page layout still lacks structure. It might be a good idea to establish a good structure now while the load of settings is still low.

**Describe the solution you'd like**
I think the best solution is to imitate something like the Chrome Browser settings page layout that most people are familiar with, where:

- All options are visible to the user in sub-sections to reduce visual load using a navigation "side panel" area of subheadings, such as
  - Appearance (for setting the aspect ratios of cards, etc)
  - Custom metadata
  - Plugins
  - About
- Per the screenshot, each sub-section is contained within a [card](https://vuematerial.io/components/card); each setting within the card is separated with a [divider](https://vuematerial.io/components/divider)
- Use the [select component](https://vuematerial.io/components/select) for a setting with multiple choice options
- Use the [switch component](https://vuematerial.io/components/switch) for binary options that can be toggled.
- If there are any hidden pages in the app, such as `/#/plugins` provide a link in the appropriate subheading/subsection aka `advanced` or `plugins`

![J6LRUJH](https://user-images.githubusercontent.com/37937507/81096176-036e6980-8ed4-11ea-8ad8-1ca68cc58495.png)

**Comment by leadwolf** [comment]
Here's a possibility:

Vertical tabs on large screens
![Screenshot from 2020-10-04 12-44-12](https://user-images.githubusercontent.com/17180727/95013487-da97ff00-0640-11eb-86b2-65d49a19bcd0.png)

Horizontal on small screens (mobile)
Portrait
![Screenshot from 2020-10-04 12-44-48](https://user-images.githubusercontent.com/17180727/95013494-e388d080-0640-11eb-8174-debf220b6e67.png)

Landscape
![Screenshot from 2020-10-04 12-44-55](https://user-images.githubusercontent.com/17180727/95013497-e8e61b00-0640-11eb-8517-ca337c35508c.png)

The tabs could also be in a navigation drawer like the filters on other pages:
![Screenshot from 2020-10-04 13-04-59](https://user-images.githubusercontent.com/17180727/95013704-4e86d700-0642-11eb-8748-5eae5805b2b3.png)
