### ISSUE TITLE
Filter by custom data fields

### ISSUE THREAD

**Issue by Cardellos** [porn-vault/porn-vault#542]
Is possible to create a filter using custom data fields in scenes manager?
And maybe customize the filter sidebar to remove and reorder stuff?
Thanks

**Comment by boi123212321** [comment]
Related to https://github.com/boi123212321/porn-vault/issues/439
aka. when the new search engine is done (0.22)

**Comment by boi123212321** [comment]
Will be introduced for actors first in 0.26
