### ISSUE TITLE
[Bug] <Title>Studios not picking automatically

### ISSUE THREAD

**Issue by cloudstrife11** [porn-vault/porn-vault#635]
**Studio bug**
Studios not picking automatically I have 200 brazzers videos and I have brazzers named the folder of the video. But its not picking automatically, when adding brazzers studio in pv. If I do it manually it works. 

(when I first started with pv it automatically added studios to studio tag. But my pv crashed and removed the studios.db in folder library and start over now it not do it automatically anymore.

**Desktop (please complete the following information):**
 - Windows 10 
 - Vivaldi/Chrome]

**Comment by boi123212321** [comment]
I just tested this in 0.23.0 - creating a studio attached it to a scene with that studio name in the scene path
