### ISSUE TITLE
[Bug] scenes dont show in order in movies

### ISSUE THREAD

**Issue by ciaron88** [porn-vault/porn-vault#669]
**Describe the bug**
Whenever I add scenes to a movie I will add Scene 1, Scene 2, Scene 3 etc... i then click on the movie and the scenes are now listed in the wrong order

**To Reproduce**
1. Create a new Movie
2. Add Scenes IN order (1,2,3,4 etc...)
3. Click on the Movie
4. Scenes are listed randomly

**Expected behavior**
The order of scenes should match the order you added the scene. e.g 1 = 1, 2 =2 etc...

**Screenshots**
I added these scenes as Episode 1, Episode 2, Episode 3, Episode 4
![Annotation 2020-07-01 173855](https://user-images.githubusercontent.com/31342057/86269525-c536b300-bbc1-11ea-8a99-8812350ba25c.png)

**Desktop:**
 - OS: Synology (Docker) 
 - Browser: Firefox
 - Version: 0.22.0

**Notes:**
Was also happening on Windows 10 - v.0.22.0-rc.3

**Comment by ciaron88** [comment]
This also occurs with how Actors are listed in scenes/images. Basically nothing except labels and custom fields are listed in correct order.

**Comment by boi123212321** [comment]
It's been a while, but it'll be fixed in 0.24.1
