### ISSUE TITLE
BULK_IMPORT_PATHS's instruction not clear. I cannot able to import

### ISSUE THREAD

**Issue by nonginei** [porn-vault/porn-vault#688]
I got the following error:

`Z:\win>vault.exe`
`  vault:message Max. memory: 8136 MB +0ms`
`  vault:message Loading Z:\\win\\config.yaml... +0ms`
`  vault:message Registered plugins`
`  vault:message [] +0ms`
`  vault:message FFMPEG set to Z:\\win\\ffmpeg.exe +0ms`
`  vault:message FFPROBE set to Z:\\win\\ffprobe.exe +0ms`
`  vault:message Check https://github.com/boi123212321/porn-vault for discussion & updates +0ms`
`  vault:warn Creating backup in backups\\kcgu9nbk... +0ms`
`  vault:message Server running on Port 3000 +0ms`
`√ Making .db files compatible (if needed)`
`√ Compacted DB`
`√ Loading DB...`
`√ Integrity check done.`
`  vault:message Importing 1 new import files... +0ms`
`  vault:error Z:\\jsondata\\sample.json: could not read file. +0ms`
`  vault:error Cannot read property 'toUpperCase' of undefined +0ms`

my sample json look like this:

```
{
  "actors": {
    "123":     {
      "name":"Test",
      "bornOn":15125125125125
   }
  }
}

```
it was work in older version....
please give me a valid json example so that i can modiffy.

please add the "CustomField"  in the example

**Comment by leadwolf** [comment]
In the current version, there is a bug that requires the nationality to be set, and for it to be a valid one.
While waiting for a fix, you must set a nationality using the two letter code in https://github.com/boi123212321/porn-vault/blob/dev/src/data/countries.ts

**Comment by boi123212321** [comment]
I have decided to remove the current bulk import with version 0.24.2+, and will come up with a more robust system going forward.
