### ISSUE TITLE
[Enhancement/Discussion] Actor page layout

### ISSUE THREAD

**Issue by leadwolf** [porn-vault/porn-vault#807]
Actor hero images are always made to fit the width of the page.  
But with an actual 2.75:1 image, on wide screens, they are sometimes cut off on the top and bottom, because there is a height limitation of 500px. This limitation is to prevent the image taking up too much of the screen, but it also prevents the height matching 1/2.75 of the page width (i.e. displayed image width).
On 16:9 screens the height taken by a 2.75:1 container, that fits to the full width of the screen, is `(16/(2.75))/9 ~= 65%` of the screen, but in reality it is more, considering the browser UI and toolbar.

Potential solutions are to:
1. maintain the 500px height limitation and set the image mode to `contain` so it does not get cut off. But there will be empty spaces on the sides.
2. remove the 500px height limitation. But the image will take a large portion of the screen.
3. move the actor avatar & metadata to a side column. The hero will then have less width, and thus less height
4. maintain the height limitation, but make it user adjustable. It can be a css value, allowing responsive units like `vh`. Images might still be cut off, but according to users' preferences.
5. increase the width ratio of the image, so it will take less of the page's height. But more than 2.75 might make it too short for the subjects of the pictures.
5. Display the hero image "underneath" the rest of the page, and have the rest of the page scroll above it
7. Other ideas ?

Current behaviour
![Screenshot from 2020-09-18 17-44-44-1](https://user-images.githubusercontent.com/17180727/93620936-185b1d80-f9db-11ea-8ebb-521e52264fbe.png)

(1) with max height, image `contain`
![Screenshot from 2020-09-18 17-52-20](https://user-images.githubusercontent.com/17180727/93620958-1ee99500-f9db-11ea-949b-4944f108dbc9.png)

(2) Without the max height
![Screenshot from 2020-09-18 17-45-05](https://user-images.githubusercontent.com/17180727/93620952-1d1fd180-f9db-11ea-902b-24fac6090497.png)

(3) split columns
![Screenshot from 2020-09-18 18-19-41](https://user-images.githubusercontent.com/17180727/93621260-94556580-f9db-11ea-81c9-7f1d635829fb.png)

**Comment by boi123212321** [comment]
I think the sidebar is the most sensible layout IF it scrolls with the viewport

**Comment by GernBlanston12** [comment]
I'm a fan of options 2 and 3, perhaps moving the bio data to the new side column in 3.  Could also move each of scenes, images and meta tabs to the drop-down above the banner image?
