### ISSUE TITLE
[Feature] Fit video player to screen width/height

### ISSUE THREAD

**Issue by leadwolf** [porn-vault/porn-vault#828]
**Is your feature request related to a problem? Please describe.**
On tall/wider screens (other than 16:9), the video player will have black bars

**Describe the solution you'd like**
Have a button in the video player, to "zoom" the player to fit either the screen height/width

Fit height
![Screenshot from 2020-09-27 11-49-27](https://user-images.githubusercontent.com/17180727/94361827-8a0c2900-00b7-11eb-83f6-9bea3668c4bf.png)

Fit width
![Screenshot from 2020-09-27 11-50-19](https://user-images.githubusercontent.com/17180727/94361859-a4de9d80-00b7-11eb-8055-7ab51b1f6276.png)

**Comment by Red5ive-UK** [comment]
Related to this, would be great to see a way to make smaller 480p and less videos be resized, maybe with a double size button or have it fill the viewport. I know we can go full screen but then you loose the markers and old vintage videos look like crap!
