### ISSUE TITLE
New actor labels being applied to scenes when the scene is edited

### ISSUE THREAD

**Issue by Herpes2000** [porn-vault/porn-vault#952]
with applyActorLabels: true in the config file

I have a library with actors already assigned to scenes. I apply a new label to the actor but it does not update the scenes with that label. When I view the scene I can add/remove labels but the new label I have applied does not appear there automatically. However if I change the scene name or edit the release date or other information in the edit window, then the scene will automatically update with the new label. 

This is confusing for the user and I am not sure what the intended behavior should be.

I would suggest that if applyActorLabels was set to true, and a new label was attached to an actor, that it should automatically update all of the scenes the actor was in with the new label.

**Comment by leadwolf** [comment]
Initial behavior was to only attach labels when items are created and not when updated. This is so, after actors/scenes are created and the initial spread of labels is over, the user can edit the labels without them being updated to linked items.  
Thus the automatic update of scene labels when an actor is updated should be a user config which is a new feature
